### ISSUE TITLE
Whenever i try to click on a role button it says : "This interaction failed" below the bots button message

### ISSUE THREAD

**Issue by MGP26** [notunderctrl/discordjs-v14-series#5]
thats my problem but also the exact problem doesnt show up in the terminal of my visual code studio application.

**Comment by EnderRobber101** [comment]
Check out the discord intents to check if it is enabled in the code and on the website

**Comment by MGP26** [comment]
@EnderRobber101 actually it was because the role of my bot was in the very bottom of the roles so it didnt had privileges. But still thank you
